### ISSUE TITLE
Support PATCH_SIZE>8 for GPU Poisson

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#121]
### Tasks
- [ ] Use SOR or MG?
- [ ] Switch to global memory
- [ ] Use L1 cache instead of shared memory
- [ ] Test the accuracy of the Poisson solver
- [ ] Reduce the number of patch groups transferring to GPU at a time

### Advantages
- Significantly improve the performance and memory consumption of `libyt` and `yt`
- Reduce the memory overhead associated with ghost zones

### Disadvantages
  - Less flexible grid refinement
  - May affect load balancing if there are too few patches
