### ISSUE TITLE
Support Grackle in cosmological simulations

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#242]
### Tasks
- [ ] Support `COMOVING + SUPPORT_GRACKLE`
  - [ ] Pass the redshift information to Grackle
  - [ ] Validate that the units of all gas fields are consistent with Grackle
  - [ ] Validate that the definitions of all comoving gas fields are consistent with Grackle
- [ ] Compare the simulation results with Enzo (and/or GIZMO)
  - [ ] Tabular cooling/heating with Cloudy
  - [ ] Non-equilibrium primordial chemistry network

### Notes
- Must finish #240 first
