### ISSUE TITLE
Clarify MAX_LEVEL

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#301]
### Goal
Regard `MAX_LEVEL` as a pure refinement criterion that can be changed during runtime or after restart. As a result, we should allow patches to exist on levels higher than `MAX_LEVEL` temporarily.

### Tasks
- [ ] `MAX_LEVEL` should only be used in refinement routines
- [ ] Replace `MAX_LEVEL` with `TOP_LEVEL` or `NPatchTotal[]` whenever appropriate
- [ ] Make sure that all routines work properly and efficiently on levels without any patch
- [ ] Test changing `MAX_LEVEL` in the following two cases
  - [ ] During runtime
  - [ ] After restart
