### ISSUE TITLE
Tracking specific particles

### ISSUE THREAD

**Issue by hyschive** [gamer-project/gamer#75]
### Goals
- [ ] Add a general interface to track specific particles

### Checklist
- [ ] Record the MPI rank and local particle ID of these target particles
- [ ] Output the attributes of target particles
  - [ ] Can be a runtime parameter 
- [ ] Parallelization
  - [ ] MPI
  - [ ] OpenMP 
- [ ] Restart
- [ ] Particle creation / deletion
- [ ] Apply to SMBH particles

### Notes
- Should we support global particle ID first?
